// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbvcQ3s9UbWPr4AVJ-JSw0V8RvIE4SwY',
    appId: '1:420701607352:web:491bf1ba61def9c137ab4d',
    messagingSenderId: '420701607352',
    projectId: 'maxstyle-3e805',
    authDomain: 'maxstyle-3e805.firebaseapp.com',
    storageBucket: 'maxstyle-3e805.appspot.com',
    measurementId: 'G-Z19NS527M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpXQEwo65E1bmc-gsOJd7s-yK_1qbxjo',
    appId: '1:420701607352:android:69226717233641ac37ab4d',
    messagingSenderId: '420701607352',
    projectId: 'maxstyle-3e805',
    storageBucket: 'maxstyle-3e805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf9IryXd8b9LXFSLWrkKXZVQINL6J0vwA',
    appId: '1:420701607352:ios:dd6f96b37cf0142637ab4d',
    messagingSenderId: '420701607352',
    projectId: 'maxstyle-3e805',
    storageBucket: 'maxstyle-3e805.appspot.com',
    iosBundleId: 'com.example.khushiCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf9IryXd8b9LXFSLWrkKXZVQINL6J0vwA',
    appId: '1:420701607352:ios:dd6f96b37cf0142637ab4d',
    messagingSenderId: '420701607352',
    projectId: 'maxstyle-3e805',
    storageBucket: 'maxstyle-3e805.appspot.com',
    iosBundleId: 'com.example.khushiCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbvcQ3s9UbWPr4AVJ-JSw0V8RvIE4SwY',
    appId: '1:420701607352:web:f829ba6aa6d1e6c737ab4d',
    messagingSenderId: '420701607352',
    projectId: 'maxstyle-3e805',
    authDomain: 'maxstyle-3e805.firebaseapp.com',
    storageBucket: 'maxstyle-3e805.appspot.com',
    measurementId: 'G-27MR6FPNJH',
  );
}
